name: Build

on:
  push:
    branches:
      - browser

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    concurrency:
      group: unity-build
      cancel-in-progress: true
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: DynamicTBS_Multiplayer/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build Windows
      - name: Build project for windows
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.6f1
          projectPath: DynamicTBS_Multiplayer
          buildMethod: BuildScript.PerformBuildWindows
      # Upload Windows
      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: Build_Windows
          path: DynamicTBS_Multiplayer/Builds/Windows
      # Build Mac
      - name: Build project for mac
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.6f1
          projectPath: DynamicTBS_Multiplayer
          buildMethod: BuildScript.PerformBuildMac
      # Upload Mac
      - name: Upload Mac Build
        uses: actions/upload-artifact@v2
        with:
          name: Build_Mac
          path: DynamicTBS_Multiplayer/Builds/Mac
      # Build WebGL
      - name: Build project for browser
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.6f1
          projectPath: DynamicTBS_Multiplayer
          buildMethod: BuildScript.PerformBuildWebGL
      # Upload WebGL
      - name: Upload WebGL Build
        uses: actions/upload-artifact@v2
        with:
          name: Build_WebGL
          path: DynamicTBS_Multiplayer/Builds/WebGL
