name: Build and Test

on:
  push:
    branches:
      - online

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download Unity
      run: |
        curl -o Unity.tar.xz https://download.unity3d.com/download_unity/2021.3.6f1/LinuxEditorInstaller/Unity-2021.3.6f1.tar.xz
        mkdir -p /opt/Unity
        tar xf Unity.tar.xz -C /opt/Unity
    - name: Cache Unity modules
      uses: actions/cache@v2
      with:
        path: "/opt/Unity/Editor/Data/PlaybackEngines"
        key: "${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}-${{ hashFiles('**/Packages/packages-lock.json') }}"
        restore-keys: |
          ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}-
          ${{ runner.os }}-unity-
    - name: Build Unity project
      run: |
        /opt/Unity/Editor/Unity -projectPath ./ -batchmode -quit -executeMethod BuildScript.PerformBuild
