name: Build and Test

on:
  push:
    branches:
      - online

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Setup Unity
      uses: game-ci/unity-setup@v1
      with:
        unityVersion: 2021.3.6f1

    - name: Build Unity project
      run: |
        /opt/unity/Editor/Unity -projectPath ./ -batchmode -executeMethod BuildScript.PerformBuild -quit
